# Generated by Django 5.2.7 on 2025-11-02 18:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tên đầy đủ của phòng khám",
                        max_length=200,
                        verbose_name="Tên phòng khám",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Phòng khám có đang hoạt động không",
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Địa chỉ chi tiết của phòng khám",
                        null=True,
                        verbose_name="Địa chỉ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Phòng khám",
                "verbose_name_plural": "Phòng khám",
                "db_table": "clinics",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="clinics_name_040576_idx"),
                    models.Index(
                        fields=["is_active"], name="clinics_is_acti_5ab494_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        help_text="Số chứng minh nhân dân hoặc căn cước công dân",
                        max_length=12,
                        unique=True,
                        verbose_name="CMND/CCCD",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Họ và tên"),
                ),
                ("date_of_birth", models.DateField(verbose_name="Ngày sinh")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Nam", "Nam"), ("Nữ", "Nữ"), ("Khác", "Khác")],
                        max_length=10,
                        verbose_name="Giới tính",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="VN", verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nghề nghiệp",
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        default="Kinh", max_length=50, verbose_name="Dân tộc"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
            ],
            options={
                "verbose_name": "Bệnh nhân",
                "verbose_name_plural": "Bệnh nhân",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["national_id"], name="users_patie_nationa_8d663f_idx"
                    ),
                    models.Index(
                        fields=["full_name"], name="users_patie_full_na_6d7179_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="users_patie_created_596bfb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_id",
                    models.CharField(
                        help_text="Mã định danh bác sĩ",
                        max_length=20,
                        unique=True,
                        verbose_name="Mã bác sĩ",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Họ và tên"),
                ),
                (
                    "specialization",
                    models.CharField(
                        help_text="Ví dụ: Tim mạch, Nội khoa, Ngoại khoa...",
                        max_length=100,
                        verbose_name="Chuyên khoa",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="VN", verbose_name="Số điện thoại"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Số năm kinh nghiệm"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Đang hoạt động"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "user_id",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tài khoản người dùng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bác sĩ",
                "verbose_name_plural": "Bác sĩ",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(
                        fields=["doctor_id"], name="users_docto_doctor__ac3364_idx"
                    ),
                    models.Index(
                        fields=["specialization"], name="users_docto_special_a3c062_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        help_text="Mã số thẻ bảo hiểm y tế",
                        max_length=30,
                        unique=True,
                        verbose_name="Số thẻ BHYT",
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="Ngày hết hạn")),
                (
                    "issued_date",
                    models.DateField(blank=True, null=True, verbose_name="Ngày cấp"),
                ),
                (
                    "insurance_type",
                    models.CharField(
                        default="BHYT",
                        help_text="Loại bảo hiểm: BHYT, BHTN, ...",
                        max_length=50,
                        verbose_name="Loại bảo hiểm",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurances",
                        to="users.patients",
                        verbose_name="Bệnh nhân",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bảo hiểm y tế",
                "verbose_name_plural": "Bảo hiểm y tế",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["insurance_number"],
                        name="users_insur_insuran_314ec2_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="users_insur_expiry__003d53_idx"
                    ),
                ],
            },
        ),
    ]
