# Generated by Django 5.2.7 on 2025-10-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_id',
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
