# Generated by Django 5.2.7 on 2025-11-05 07:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('prices_non_insurance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá dịch vụ không bảo hiểm')),
                ('prices_insurance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá dịch vụ có bảo hiểm')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại liên hệ', max_length=20, null=True, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, help_text='Địa chỉ chi tiết', null=True, verbose_name='Địa chỉ')),
                ('role', models.CharField(choices=[('admin', 'Quản trị viên'), ('doctor', 'Bác sĩ'), ('nurse', 'Y tá'), ('receptionist', 'Lễ tân'), ('accountant', 'Kế toán'), ('pharmacist', 'Dược sĩ'), ('technician', 'Kỹ thuật viên')], default='receptionist', help_text='Vai trò của người dùng trong hệ thống', max_length=20, verbose_name='Vai trò')),
                ('department', models.CharField(blank=True, help_text='Ví dụ: Khoa Nội, Khoa Ngoại, Phòng Kế toán...', max_length=100, null=True, verbose_name='Khoa/Phòng ban')),
                ('employee_id', models.CharField(blank=True, help_text='Mã nhân viên duy nhất (VD: NV001, BS123...)', max_length=20, null=True, unique=True, verbose_name='Mã nhân viên')),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện của người dùng', null=True, upload_to='avatars/%Y/%m/', verbose_name='Ảnh đại diện')),
                ('date_of_birth', models.DateField(blank=True, help_text='Ngày sinh của người dùng', null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True, verbose_name='Giới tính')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm về người dùng', null=True, verbose_name='Ghi chú')),
                ('created_by', models.ForeignKey(blank=True, help_text='Người dùng đã tạo tài khoản này', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'custom_users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên đầy đủ của phòng khám', max_length=200, verbose_name='Tên phòng khám')),
                ('is_active', models.BooleanField(default=True, help_text='Phòng khám có đang hoạt động không', verbose_name='Trạng thái')),
                ('address', models.TextField(blank=True, help_text='Địa chỉ chi tiết của phòng khám', null=True, verbose_name='Địa chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Phòng khám',
                'verbose_name_plural': 'Phòng khám',
                'db_table': 'clinics',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clinics_name_040576_idx'), models.Index(fields=['is_active'], name='clinics_is_acti_5ab494_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(help_text='Mã định danh bác sĩ', max_length=20, unique=True, verbose_name='Mã bác sĩ')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('specialization', models.CharField(help_text='Ví dụ: Tim mạch, Nội khoa, Ngoại khoa...', max_length=100, verbose_name='Chuyên khoa')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VN', verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='Số năm kinh nghiệm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Bác sĩ',
                'verbose_name_plural': 'Bác sĩ',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('citizen_id', models.CharField(help_text='Số căn cước công dân', max_length=12, primary_key=True, serialize=False, verbose_name='Số CCCD')),
                ('insurance_id', models.CharField(help_text='Mã số thẻ bảo hiểm y tế', max_length=30, unique=True, verbose_name='Mã thẻ BHYT')),
                ('fullname', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('gender', models.IntegerField(choices=[(1, 'Nam'), (0, 'Nữ')], help_text='1=Nam, 0=Nữ', verbose_name='Giới tính')),
                ('dob', models.DateField(verbose_name='Ngày sinh')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('registration_place', models.CharField(help_text='Bệnh viện đăng ký khám chữa bệnh ban đầu', max_length=255, verbose_name='Nơi đăng ký KCB')),
                ('valid_from', models.DateField(verbose_name='Ngày bắt đầu hiệu lực')),
                ('expired', models.DateField(verbose_name='Ngày hết hạn')),
            ],
            options={
                'verbose_name': 'Bảo hiểm y tế',
                'verbose_name_plural': 'Bảo hiểm y tế',
                'ordering': ['-expired'],
                'indexes': [models.Index(fields=['insurance_id'], name='kiosk_insur_insuran_110c76_idx'), models.Index(fields=['expired'], name='kiosk_insur_expired_48a145_idx')],
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='Số căn cước công dân', max_length=12, unique=True, verbose_name='CMND/CCCD')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('date_of_birth', models.DateField(verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10, verbose_name='Giới tính')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='VN', verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Địa chỉ')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nghề nghiệp')),
                ('ethnicity', models.CharField(default='Kinh', max_length=50, verbose_name='Dân tộc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Bệnh nhân',
                'verbose_name_plural': 'Bệnh nhân',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['national_id'], name='kiosk_patie_nationa_0a7392_idx'), models.Index(fields=['full_name'], name='kiosk_patie_full_na_fc8912_idx'), models.Index(fields=['-created_at'], name='kiosk_patie_created_05c920_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['employee_id'], name='custom_user_employe_e22f63_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='custom_user_role_1a5fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='custom_user_departm_d2743f_idx'),
        ),
        migrations.AddIndex(
            model_name='doctors',
            index=models.Index(fields=['doctor_id'], name='kiosk_docto_doctor__c41081_idx'),
        ),
        migrations.AddIndex(
            model_name='doctors',
            index=models.Index(fields=['specialization'], name='kiosk_docto_special_dc5684_idx'),
        ),
    ]
