# Generated by Django 5.2.7 on 2025-11-10 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('queue_number', models.PositiveIntegerField(blank=True, help_text='Số thứ tự trong hàng đợi', null=True, verbose_name='Số thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo đơn hàng', verbose_name='Thời gian tạo')),
                ('order_status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', help_text='Trạng thái hiện tại của đơn hàng', max_length=20, verbose_name='Trạng thái đơn hàng')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('card', 'Thẻ tín dụng'), ('transfer', 'Chuyển khoản'), ('insurance', 'Bảo hiểm')], help_text='Cách thức thanh toán', max_length=20, null=True, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', help_text='Trạng thái thanh toán', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('prices', models.DecimalField(blank=True, decimal_places=2, help_text='Tổng giá trị đơn hàng', max_digits=10, null=True, verbose_name='Giá tiền')),
                ('citizen', models.ForeignKey(help_text='Bệnh nhân đặt lịch', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='kiosk.patients', verbose_name='Bệnh nhân')),
                ('clinic_service', models.ForeignKey(help_text='Dịch vụ/phòng khám được chọn', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='kiosk.serviceexam', verbose_name='Dịch vụ khám')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['citizen'], name='kiosk_order_citizen_a07992_idx'), models.Index(fields=['clinic_service'], name='kiosk_order_clinic__e4b22f_idx'), models.Index(fields=['order_status'], name='kiosk_order_order_s_766707_idx'), models.Index(fields=['payment_status'], name='kiosk_order_payment_747be8_idx'), models.Index(fields=['-created_at'], name='kiosk_order_created_6dc70a_idx')],
            },
        ),
    ]
